export interface ParameterInfo {
  display_name: string;
  reference_range: string;
  units: string | null;
  min_value: number | null;
  max_value: number | null;
}

/** Matches ArterialAnalysisParameter order in e-next-backend/app/investigation_reports/enums.py */
export const arterialParameterOrder: string[] = [
  'pH',
  'pCO2',
  'pO2',
  'HCO3',
  'Base Excess',
  'Lactate (ABG)',
  'Sodium (ABG)',
  'Potassium (ABG)',
  'Chloride (ABG)',
  'Calcium Ionized (ABG)',
  'Anion Gap',
  'Glucose (ABG)',
  'Hemoglobin (ABG)',
  'Hematocrit (ABG)',
  'sO2',
];

export const arterialBloodGasParameterInfo: { [key: string]: ParameterInfo } = {
  "pH": {
    display_name: "pH",
    reference_range: "7.35 – 7.45",
    units: null,
    min_value: 7.35,
    max_value: 7.45,
  },
  "pCO2": {
    display_name: "pCO2",
    reference_range: "35 – 45",
    units: "mmHg",
    min_value: 35,
    max_value: 45,
  },
  "pO2": {
    display_name: "pO2",
    reference_range: "80 – 100",
    units: "mmHg",
    min_value: 80,
    max_value: 100,
  },
  "HCO3": {
    display_name: "HCO3",
    reference_range: "22 – 26",
    units: "mmol/L",
    min_value: 22,
    max_value: 26,
  },
  "HCO3 Actual": {
    display_name: "HCO3 Actual",
    reference_range: "22 – 26",
    units: "mmol/L",
    min_value: 22,
    max_value: 26,
  },
  "HCO3 Standard": {
    display_name: "HCO3 Standard",
    reference_range: "22 – 26",
    units: "mmol/L",
    min_value: 22,
    max_value: 26,
  },
  "sO2": {
    display_name: "sO2",
    reference_range: "95 – 100",
    units: "%",
    min_value: 95,
    max_value: 100,
  },
  "FiO2": {
    display_name: "FiO2",
    reference_range: "21 – 100",
    units: "%",
    min_value: 21,
    max_value: 100,
  },
  "PaO2/FiO2 Ratio": {
    display_name: "PaO2/FiO2 Ratio",
    reference_range: "> 300",
    units: null,
    min_value: 300,
    max_value: null,
  },
  "A-a Gradient": {
    display_name: "A-a Gradient",
    reference_range: "< 15",
    units: "mmHg",
    min_value: null,
    max_value: 15,
  },
  "Sodium (ABG)": {
    display_name: "Sodium (ABG)",
    reference_range: "135 – 145",
    units: "mmol/L",
    min_value: 135,
    max_value: 145,
  },
  "Potassium (ABG)": {
    display_name: "Potassium (ABG)",
    reference_range: "3.5 – 5.0",
    units: "mmol/L",
    min_value: 3.5,
    max_value: 5.0,
  },
  "Chloride (ABG)": {
    display_name: "Chloride (ABG)",
    reference_range: "98 – 107",
    units: "mmol/L",
    min_value: 98,
    max_value: 107,
  },
  "Calcium Ionized (ABG)": {
    display_name: "Calcium Ionized (ABG)",
    reference_range: "1.12 – 1.32",
    units: "mmol/L",
    min_value: 1.12,
    max_value: 1.32,
  },
  "Base Excess": {
    display_name: "Base Excess",
    reference_range: "-2 – +2",
    units: "mmol/L",
    min_value: -2,
    max_value: 2,
  },
  "Base Deficit": {
    display_name: "Base Deficit",
    reference_range: "-2 – +2",
    units: "mmol/L",
    min_value: -2,
    max_value: 2,
  },
  "Anion Gap": {
    display_name: "Anion Gap",
    reference_range: "8 – 12",
    units: "mmol/L",
    min_value: 8,
    max_value: 12,
  },
  "Lactate (ABG)": {
    display_name: "Lactate (ABG)",
    reference_range: "0.5 – 2.2",
    units: "mmol/L",
    min_value: 0.5,
    max_value: 2.2,
  },
  "Glucose (ABG)": {
    display_name: "Glucose (ABG)",
    reference_range: "70 – 100 (fasting)",
    units: "mg/dL",
    min_value: 70,
    max_value: 100,
  },
  "Hemoglobin (ABG)": {
    display_name: "Hemoglobin (ABG)",
    reference_range: "12.0 – 16.0 (female) / 13.5 – 17.5 (male)",
    units: "g/dL",
    min_value: 12.0,
    max_value: 17.5,
  },
  "Hematocrit (ABG)": {
    display_name: "Hematocrit (ABG)",
    reference_range: "36 – 46 (female) / 41 – 53 (male)",
    units: "%",
    min_value: 36,
    max_value: 53,
  },
  "COHb": {
    display_name: "COHb",
    reference_range: "< 2",
    units: "%",
    min_value: null,
    max_value: 2,
  },
  "MetHb": {
    display_name: "MetHb",
    reference_range: "< 1.5",
    units: "%",
    min_value: null,
    max_value: 1.5,
  },
  "pH (Temp Corrected)": {
    display_name: "pH (Temp Corrected)",
    reference_range: "7.35 – 7.45",
    units: null,
    min_value: 7.35,
    max_value: 7.45,
  },
  "pCO2 (Temp Corrected)": {
    display_name: "pCO2 (Temp Corrected)",
    reference_range: "35 – 45",
    units: "mmHg",
    min_value: 35,
    max_value: 45,
  },
  "pO2 (Temp Corrected)": {
    display_name: "pO2 (Temp Corrected)",
    reference_range: "80 – 100",
    units: "mmHg",
    min_value: 80,
    max_value: 100,
  },
};
