export interface ParameterInfo {
  display_name: string;
  reference_range: string;
  units: string | null;
  min_value: number | null;
  max_value: number | null;
}

/** Matches BloodAnalysisParameter order in e-next-backend/app/investigation_reports/enums.py */
export const bloodParameterOrder: string[] = [
  'Haemoglobin',
  'RBC Count',
  'WBC Count',
  'Platelet Count',
  'Neutrophils',
  'PCV/Hematocrit',
  'MCV',
  'MCH',
  'MCHC',
  'MPV',
  'Lymphocytes',
  'Monocytes',
  'Basophils',
  'Absolute Neutrophil Count',
  'Absolute Lymphocyte',
  'Absolute Monocyte',
  'PT',
  'INR',
  'aPTT',
  'Albumin',
  'Total Bilirubin',
  'Direct Bilirubin',
  'Indirect Bilirubin',
  'SGPT/ALT',
  'SGOT/AST',
  'Alkaline Phosphatase',
  'GGT',
  'Total Protein',
  'Blood Urea',
  'Serum Creatinine',
  'Uric Acid',
  'Sodium',
  'Potassium',
  'Bicarbonate',
  'Chloride',
  'Phosphorus',
  'Calcium',
  'Calcium Total',
  'Magnesium',
  'CPK Total',
  'CPK-MB',
  'Troponin I',
  'T3 Total',
  'T4 Total',
  'TSH',
  'Ammonia',
  'ESR',
  'CRP',
  'Amylase',
  'Lipase',
  'Procalcitonin',
  'HIV',
  'HBsAg',
  'HCV',
];

export const qualitativeBloodParameters = ['HIV', 'HBsAg', 'HCV'] as const;

export const qualitativeBloodParameterSet = new Set<string>(qualitativeBloodParameters);

export const bloodParameterInfo: { [key: string]: ParameterInfo } = {
  "Haemoglobin": {
    display_name: "Haemoglobin",
    reference_range: "12.0 - 15.0",
    units: "g/dL",
    min_value: 12.0,
    max_value: 15.0,
  },
  "RBC Count": {
    display_name: "RBC Count",
    reference_range: "4.5 - 5.9",
    units: "million cells/µL",
    min_value: 4.5,
    max_value: 5.9,
  },
  "WBC Count": {
    display_name: "WBC Count",
    reference_range: "4.0 - 11.0",
    units: "thousand cells/µL",
    min_value: 4.0,
    max_value: 11.0,
  },
  "Platelet Count": {
    display_name: "Platelet Count",
    reference_range: "150 - 450",
    units: "thousand cells/µL",
    min_value: 150,
    max_value: 450,
  },
  "PCV/Hematocrit": {
    display_name: "PCV/Hematocrit",
    reference_range: "38.0 - 50.0",
    units: "%",
    min_value: 38.0,
    max_value: 50.0,
  },
  "MCV": {
    display_name: "MCV",
    reference_range: "80 - 100",
    units: "fL",
    min_value: 80,
    max_value: 100,
  },
  "MCH": {
    display_name: "MCH",
    reference_range: "27 - 33",
    units: "pg",
    min_value: 27,
    max_value: 33,
  },
  "MCHC": {
    display_name: "MCHC",
    reference_range: "32 - 36",
    units: "g/dL",
    min_value: 32,
    max_value: 36,
  },
  "RDW": {
    display_name: "RDW",
    reference_range: "11.5 - 14.5",
    units: "%",
    min_value: 11.5,
    max_value: 14.5,
  },
  "MPV": {
    display_name: "MPV",
    reference_range: "7.5 - 11.5",
    units: "fL",
    min_value: 7.5,
    max_value: 11.5,
  },
  "Neutrophils": {
    display_name: "Neutrophils",
    reference_range: "40 - 60",
    units: "%",
    min_value: 40,
    max_value: 60,
  },
  "Lymphocytes": {
    display_name: "Lymphocytes",
    reference_range: "20 - 40",
    units: "%",
    min_value: 20,
    max_value: 40,
  },
  "Monocytes": {
    display_name: "Monocytes",
    reference_range: "2 - 8",
    units: "%",
    min_value: 2,
    max_value: 8,
  },
  "Eosinophils": {
    display_name: "Eosinophils",
    reference_range: "1 - 4",
    units: "%",
    min_value: 1,
    max_value: 4,
  },
  "Basophils": {
    display_name: "Basophils",
    reference_range: "0.5 - 1",
    units: "%",
    min_value: 0.5,
    max_value: 1,
  },
  "Absolute Lymphocyte": {
    display_name: "Absolute Lymphocyte",
    reference_range: "1500 - 8000",
    units: "cells/µL",
    min_value: 1500,
    max_value: 8000,
  },
  "Absolute Monocyte": {
    display_name: "Absolute Monocyte",
    reference_range: "200 - 800",
    units: "cells/µL",
    min_value: 200,
    max_value: 800,
  },
  "Absolute Neutrophil Count": {
    display_name: "Absolute Neutrophil Count",
    reference_range: "1500 - 8000",
    units: "cells/µL",
    min_value: 1500,
    max_value: 8000,
  },
  "Blood Urea": {
    display_name: "Blood Urea",
    reference_range: "7 - 20",
    units: "mg/dL",
    min_value: 7,
    max_value: 20,
  },
  "Serum Creatinine": {
    display_name: "Serum Creatinine",
    reference_range: "0.6 - 1.2",
    units: "mg/dL",
    min_value: 0.6,
    max_value: 1.2,
  },
  "BUN": {
    display_name: "BUN",
    reference_range: "7 - 20",
    units: "mg/dL",
    min_value: 7,
    max_value: 20,
  },
  "eGFR": {
    display_name: "eGFR",
    reference_range: ">90",
    units: "mL/min/1.73 m²",
    min_value: 90,
    max_value: null,
  },
  "Cystatin C": {
    display_name: "Cystatin C",
    reference_range: "0.51 - 1.00",
    units: "mg/L",
    min_value: 0.51,
    max_value: 1.00,
  },
  "Sodium": {
    display_name: "Sodium",
    reference_range: "135 - 145",
    units: "mmol/L",
    min_value: 135,
    max_value: 145,
  },
  "Potassium": {
    display_name: "Potassium",
    reference_range: "3.5 - 5.1",
    units: "mmol/L",
    min_value: 3.5,
    max_value: 5.1,
  },
  "Chloride": {
    display_name: "Chloride",
    reference_range: "98 - 107",
    units: "mmol/L",
    min_value: 98,
    max_value: 107,
  },
  "Bicarbonate": {
    display_name: "Bicarbonate",
    reference_range: "22 - 29",
    units: "mmol/L",
    min_value: 22,
    max_value: 29,
  },
  "Calcium": {
    display_name: "Calcium Total",
    reference_range: "8.6 - 10.3",
    units: "mg/dL",
    min_value: 8.6,
    max_value: 10.3,
  },
  "Calcium Total": {
    display_name: "Calcium Total",
    reference_range: "8.6 - 10.3",
    units: "mg/dL",
    min_value: 8.6,
    max_value: 10.3,
  },
  "Calcium Ionized": {
    display_name: "Calcium Ionized",
    reference_range: "4.65 - 5.28",
    units: "mg/dL",
    min_value: 4.65,
    max_value: 5.28,
  },
  "Magnesium": {
    display_name: "Magnesium",
    reference_range: "1.7 - 2.2",
    units: "mg/dL",
    min_value: 1.7,
    max_value: 2.2,
  },
  "Phosphorus": {
    display_name: "Phosphorus",
    reference_range: "2.5 - 4.5",
    units: "mg/dL",
    min_value: 2.5,
    max_value: 4.5,
  },
  "Total Bilirubin": {
    display_name: "Total Bilirubin",
    reference_range: "0.1 - 1.2",
    units: "mg/dL",
    min_value: 0.1,
    max_value: 1.2,
  },
  "Direct Bilirubin": {
    display_name: "Direct Bilirubin",
    reference_range: "0.0 - 0.3",
    units: "mg/dL",
    min_value: 0.0,
    max_value: 0.3,
  },
  "Indirect Bilirubin": {
    display_name: "Indirect Bilirubin",
    reference_range: "0.2 - 0.8",
    units: "mg/dL",
    min_value: 0.2,
    max_value: 0.8,
  },
  "SGOT/AST": {
    display_name: "SGOT/AST",
    reference_range: "10 - 40",
    units: "U/L",
    min_value: 10,
    max_value: 40,
  },
  "SGPT/ALT": {
    display_name: "SGPT/ALT",
    reference_range: "7 - 56",
    units: "U/L",
    min_value: 7,
    max_value: 56,
  },
  "Alkaline Phosphatase": {
    display_name: "Alkaline Phosphatase",
    reference_range: "44 - 147",
    units: "U/L",
    min_value: 44,
    max_value: 147,
  },
  "GGT": {
    display_name: "GGT",
    reference_range: "9 - 48",
    units: "U/L",
    min_value: 9,
    max_value: 48,
  },
  "Total Protein": {
    display_name: "Total Protein",
    reference_range: "6.0 - 8.3",
    units: "g/dL",
    min_value: 6.0,
    max_value: 8.3,
  },
  "Albumin": {
    display_name: "Albumin",
    reference_range: "3.5 - 5.0",
    units: "g/dL",
    min_value: 3.5,
    max_value: 5.0,
  },
  "Globulin": {
    display_name: "Globulin",
    reference_range: "2.0 - 3.5",
    units: "g/dL",
    min_value: 2.0,
    max_value: 3.5,
  },
  "A/G Ratio": {
    display_name: "A/G Ratio",
    reference_range: "1.0 - 2.1",
    units: null,
    min_value: 1.0,
    max_value: 2.1,
  },
  "Troponin I": {
    display_name: "Troponin I",
    reference_range: "< 0.04",
    units: "ng/mL",
    min_value: null,
    max_value: 0.04,
  },
  "Troponin T": {
    display_name: "Troponin T",
    reference_range: "< 0.01",
    units: "ng/mL",
    min_value: null,
    max_value: 0.01,
  },
  "CPK Total": {
    display_name: "CPK Total",
    reference_range: "30 - 200",
    units: "U/L",
    min_value: 30,
    max_value: 200,
  },
  "CPK-MB": {
    display_name: "CPK-MB",
    reference_range: "0 - 25",
    units: "U/L",
    min_value: 0,
    max_value: 25,
  },
  "LDH": {
    display_name: "LDH",
    reference_range: "140 - 280",
    units: "U/L",
    min_value: 140,
    max_value: 280,
  },
  "Pro-BNP": {
    display_name: "Pro-BNP",
    reference_range: "< 125",
    units: "pg/mL",
    min_value: null,
    max_value: 125,
  },
  "NT-proBNP": {
    display_name: "NT-proBNP",
    reference_range: "< 300",
    units: "pg/mL",
    min_value: null,
    max_value: 300,
  },
  "Myoglobin": {
    display_name: "Myoglobin",
    reference_range: "28 - 72",
    units: "ng/mL",
    min_value: 28,
    max_value: 72,
  },
  "PT": {
    display_name: "PT",
    reference_range: "11 - 13.5",
    units: "seconds",
    min_value: 11,
    max_value: 13.5,
  },
  "PTT": {
    display_name: "PTT",
    reference_range: "25 - 35",
    units: "seconds",
    min_value: 25,
    max_value: 35,
  },
  "aPTT": {
    display_name: "aPTT",
    reference_range: "30 - 40",
    units: "seconds",
    min_value: 30,
    max_value: 40,
  },
  "INR": {
    display_name: "INR",
    reference_range: "0.8 - 1.1",
    units: null,
    min_value: 0.8,
    max_value: 1.1,
  },
  "Fibrinogen": {
    display_name: "Fibrinogen",
    reference_range: "200 - 400",
    units: "mg/dL",
    min_value: 200,
    max_value: 400,
  },
  "D-Dimer": {
    display_name: "D-Dimer",
    reference_range: "< 500",
    units: "ng/mL FEU",
    min_value: null,
    max_value: 500,
  },
  "FDP": {
    display_name: "FDP",
    reference_range: "< 10",
    units: "µg/mL",
    min_value: null,
    max_value: 10,
  },
  "Bleeding Time": {
    display_name: "Bleeding Time",
    reference_range: "2 - 7",
    units: "minutes",
    min_value: 2,
    max_value: 7,
  },
  "Clotting Time": {
    display_name: "Clotting Time",
    reference_range: "5 - 15",
    units: "minutes",
    min_value: 5,
    max_value: 15,
  },
  "TSH": {
    display_name: "TSH",
    reference_range: "0.4 - 4.0",
    units: "µIU/mL",
    min_value: 0.4,
    max_value: 4.0,
  },
  "T3 Total": {
    display_name: "T3 Total",
    reference_range: "80 - 200",
    units: "ng/dL",
    min_value: 80,
    max_value: 200,
  },
  "T4 Total": {
    display_name: "T4 Total",
    reference_range: "5.0 - 12.0",
    units: "µg/dL",
    min_value: 5.0,
    max_value: 12.0,
  },
  "Free T3": {
    display_name: "Free T3",
    reference_range: "2.3 - 4.2",
    units: "pg/mL",
    min_value: 2.3,
    max_value: 4.2,
  },
  "Free T4": {
    display_name: "Free T4",
    reference_range: "0.8 - 2.0",
    units: "ng/dL",
    min_value: 0.8,
    max_value: 2.0,
  },
  "Anti-TPO": {
    display_name: "Anti-TPO",
    reference_range: "< 35",
    units: "IU/mL",
    min_value: null,
    max_value: 35,
  },
  "Anti-Thyroglobulin": {
    display_name: "Anti-Thyroglobulin",
    reference_range: "< 20",
    units: "IU/mL",
    min_value: null,
    max_value: 20,
  },
  "Total Cholesterol": {
    display_name: "Total Cholesterol",
    reference_range: "< 200",
    units: "mg/dL",
    min_value: null,
    max_value: 200,
  },
  "LDL Cholesterol": {
    display_name: "LDL Cholesterol",
    reference_range: "< 100",
    units: "mg/dL",
    min_value: null,
    max_value: 100,
  },
  "HDL Cholesterol": {
    display_name: "HDL Cholesterol",
    reference_range: "40 - 60",
    units: "mg/dL",
    min_value: 40,
    max_value: 60,
  },
  "VLDL Cholesterol": {
    display_name: "VLDL Cholesterol",
    reference_range: "5 - 40",
    units: "mg/dL",
    min_value: 5,
    max_value: 40,
  },
  "Triglycerides": {
    display_name: "Triglycerides",
    reference_range: "< 150",
    units: "mg/dL",
    min_value: null,
    max_value: 150,
  },
  "Fasting Glucose": {
    display_name: "Fasting Glucose",
    reference_range: "70 - 99",
    units: "mg/dL",
    min_value: 70,
    max_value: 99,
  },
  "Postprandial Glucose": {
    display_name: "Postprandial Glucose",
    reference_range: "< 140",
    units: "mg/dL",
    min_value: null,
    max_value: 140,
  },
  "Random Glucose": {
    display_name: "Random Glucose",
    reference_range: "70 - 140",
    units: "mg/dL",
    min_value: 70,
    max_value: 140,
  },
  "HbA1c": {
    display_name: "HbA1c",
    reference_range: "4.0 - 5.6",
    units: "%",
    min_value: 4.0,
    max_value: 5.6,
  },
  "Insulin": {
    display_name: "Insulin",
    reference_range: "2.6 - 24.9",
    units: "µIU/mL",
    min_value: 2.6,
    max_value: 24.9,
  },
  "C-Peptide": {
    display_name: "C-Peptide",
    reference_range: "0.78 - 1.89",
    units: "ng/mL",
    min_value: 0.78,
    max_value: 1.89,
  },
  "CRP": {
    display_name: "CRP",
    reference_range: "< 1.0",
    units: "mg/dL",
    min_value: null,
    max_value: 1.0,
  },
  "hs-CRP": {
    display_name: "hs-CRP",
    reference_range: "< 3.0",
    units: "mg/L",
    min_value: null,
    max_value: 3.0,
  },
  "ESR": {
    display_name: "ESR",
    reference_range: "0 - 20",
    units: "mm/hr",
    min_value: 0,
    max_value: 20,
  },
  "Procalcitonin": {
    display_name: "Procalcitonin",
    reference_range: "< 0.05",
    units: "ng/mL",
    min_value: null,
    max_value: 0.05,
  },
  "HIV": {
    display_name: "HIV",
    reference_range: "Non-reactive",
    units: null,
    min_value: null,
    max_value: null,
  },
  "HBsAg": {
    display_name: "HBsAg",
    reference_range: "Non-reactive",
    units: null,
    min_value: null,
    max_value: null,
  },
  "HCV": {
    display_name: "HCV",
    reference_range: "Non-reactive",
    units: null,
    min_value: null,
    max_value: null,
  },
  "Ferritin": {
    display_name: "Ferritin",
    reference_range: "20 - 300",
    units: "ng/mL",
    min_value: 20,
    max_value: 300,
  },
  "IL-6": {
    display_name: "IL-6",
    reference_range: "< 7",
    units: "pg/mL",
    min_value: null,
    max_value: 7,
  },
  "Serum Iron": {
    display_name: "Serum Iron",
    reference_range: "60 - 170",
    units: "µg/dL",
    min_value: 60,
    max_value: 170,
  },
  "TIBC": {
    display_name: "TIBC",
    reference_range: "240 - 450",
    units: "µg/dL",
    min_value: 240,
    max_value: 450,
  },
  "Transferrin Saturation": {
    display_name: "Transferrin Saturation",
    reference_range: "20 - 50",
    units: "%",
    min_value: 20,
    max_value: 50,
  },
  "Transferrin": {
    display_name: "Transferrin",
    reference_range: "200 - 360",
    units: "mg/dL",
    min_value: 200,
    max_value: 360,
  },
  "Vitamin B12": {
    display_name: "Vitamin B12",
    reference_range: "200 - 900",
    units: "pg/mL",
    min_value: 200,
    max_value: 900,
  },
  "Folate": {
    display_name: "Folate",
    reference_range: "2.7 - 17.0",
    units: "ng/mL",
    min_value: 2.7,
    max_value: 17.0,
  },
  "Vitamin D": {
    display_name: "Vitamin D",
    reference_range: "30 - 100",
    units: "ng/mL",
    min_value: 30,
    max_value: 100,
  },
  "Cortisol": {
    display_name: "Cortisol",
    reference_range: "6 - 23",
    units: "µg/dL",
    min_value: 6,
    max_value: 23,
  },
  "Testosterone": {
    display_name: "Testosterone",
    reference_range: "300 - 1000",
    units: "ng/dL",
    min_value: 300,
    max_value: 1000,
  },
  "Prolactin": {
    display_name: "Prolactin",
    reference_range: "5 - 20",
    units: "ng/mL",
    min_value: 5,
    max_value: 20,
  },
  "LH": {
    display_name: "LH",
    reference_range: "1.8 - 8.6",
    units: "IU/L",
    min_value: 1.8,
    max_value: 8.6,
  },
  "FSH": {
    display_name: "FSH",
    reference_range: "1.5 - 12.4",
    units: "IU/L",
    min_value: 1.5,
    max_value: 12.4,
  },
  "Estradiol": {
    display_name: "Estradiol",
    reference_range: "15 - 350",
    units: "pg/mL",
    min_value: 15,
    max_value: 350,
  },
  "Progesterone": {
    display_name: "Progesterone",
    reference_range: "0.2 - 25",
    units: "ng/mL",
    min_value: 0.2,
    max_value: 25,
  },
  "AFP": {
    display_name: "AFP",
    reference_range: "< 10",
    units: "ng/mL",
    min_value: null,
    max_value: 10,
  },
  "CEA": {
    display_name: "CEA",
    reference_range: "< 5",
    units: "ng/mL",
    min_value: null,
    max_value: 5,
  },
  "CA-125": {
    display_name: "CA-125",
    reference_range: "< 35",
    units: "U/mL",
    min_value: null,
    max_value: 35,
  },
  "CA 19-9": {
    display_name: "CA 19-9",
    reference_range: "< 37",
    units: "U/mL",
    min_value: null,
    max_value: 37,
  },
  "PSA": {
    display_name: "PSA",
    reference_range: "< 4.0",
    units: "ng/mL",
    min_value: null,
    max_value: 4.0,
  },
  "Free PSA": {
    display_name: "Free PSA",
    reference_range: "Free PSA % > 25%",
    units: "ng/mL",
    min_value: null,
    max_value: null,
  },
  "Uric Acid": {
    display_name: "Uric Acid",
    reference_range: "3.5 - 7.2",
    units: "mg/dL",
    min_value: 3.5,
    max_value: 7.2,
  },
  "Ammonia": {
    display_name: "Ammonia",
    reference_range: "15 - 45",
    units: "µmol/L",
    min_value: 15,
    max_value: 45,
  },
  "Lactate": {
    display_name: "Lactate",
    reference_range: "0.5 - 2.2",
    units: "mmol/L",
    min_value: 0.5,
    max_value: 2.2,
  },
  "Amylase": {
    display_name: "Amylase",
    reference_range: "30 - 110",
    units: "U/L",
    min_value: 30,
    max_value: 110,
  },
  "Lipase": {
    display_name: "Lipase",
    reference_range: "0 - 160",
    units: "U/L",
    min_value: 0,
    max_value: 160,
  },
  "G6PD": {
    display_name: "G6PD",
    reference_range: "5.5 - 20.5",
    units: "U/g Hb",
    min_value: 5.5,
    max_value: 20.5,
  },
  "Osmolality": {
    display_name: "Osmolality",
    reference_range: "275 - 295",
    units: "mOsm/kg",
    min_value: 275,
    max_value: 295,
  }
}; 